### ISSUE TITLE
Check-list for beta release

### ISSUE THREAD

**Issue by johnpankowicz** [govmeeting/govmeeting#135]
Most of the items listed here exist as separate issues, with a "beta" label.

The items are arranged here in the order in which a user would use each feature. For example, first they would register, then login, register their local government entity (if not already registered), etc.

- [ ] User registration - #47
- [ ] Login / Logout
- [ ] GovEntity registation - issue #62
- [ ] Retrieve most recent meeting video
- [ ] Transcribe meeting in cloud
- [ ] Auto insert section tags - issue #114
- [ ] Manager review - issue #84
This is a review that nothing drastically went wrong with the video retrieval or the insertion of section tags.
A manager review also occurs after the meeting is edited.
- [ ] Edit meeting - issue #99
- [ ] Populate database - issue #96
- [ ] Browse meeting - issue #100, 
- [ ] User alerts - issue #20
- [ ] Create speaker voice samples - issue #101
